### ISSUE TITLE
bower install knockout.validation points to old repo

### ISSUE THREAD

**Issue by psyrendust** [Knockout-Contrib/Knockout-Validation#304]
`bower search knockout.validation` points to `git://github.com/ericmbarnard/Knockout-Validation` instead of `git://github.com/Knockout-Contrib/Knockout-Validation`

**Comment by crissdev** [comment]
Installation notes are now available in Readme.md for all supported installs - Bower, npm and NuGet.


For bower, the following command should retrieve version `2.0.0` along with the most recent version of KnockoutJS.

```sh
bower install knockout-validation
```

**Comment by unsafecode** [comment]
Looks like we lost something: we have a project with a reference to *bower-knockout-validation* that downloaded v2.0.3, while the new package returns v.2.0.0

I've compared the two, and it looks like there are differences. Can we please align the two?

**Comment by crissdev** [comment]
@unsafecode `bower-knockout-validation` was just a way to have this library retrieved through Bower without targeting the `master` branch (e.g `bower install knockout-validation#master`). At some point I didn't update the fork anymore because we were very close to release v2. So `bower-knockout-validation` was just a temporary solution - don't worry about differences between the two.

You should update your Bower configuration to use this repository instead. Consider reading the `Breaking changes` section in the release notes.
