### ISSUE TITLE
async Validation doesn't support caching of responses

### ISSUE THREAD

**Issue by fbuchinger** [Knockout-Contrib/Knockout-Validation#341]
async validation seems to have problems when a caching mechanism is implemented in the validation handler (use case: prevent unnecessary server requests for repeated inputs). the validation message isn't shown when the remote validation message comes from the cache and not from the async request.

demo:
http://jsfiddle.net/fbuchinger/KVxNN/6/

**Comment by jhsowter** [comment]
Hi

I had the same issue where my validation callback would occur immediately certain data was already cached. The reason is because "validateObservable" in the knockout-validation source code sets the current "valid" value to true after the async call returns. 

Your linked fiddler fixes the issue, but it could be included in the knockout-validation source code. Have you issued a pull request to that effect?

**Comment by crissdev** [comment]
The fix for this seems pretty straightforward. `validateAsync` should execute async - `ko.validation.utils.async`. @jhsowter Would you like to submit a PR for this?

Updated fiddle http://jsfiddle.net/mk9bxnLr/

**Comment by jhsowter** [comment]
I'd love to make a PR. Just need time to fork. Probably be done within 24hr.

**Comment by crissdev** [comment]
No need to rush. This is for the 2.1.0 release. Consider writing some unit tests too. If you need any help just leave a comment here. Thanks.
:+1:
