### ISSUE TITLE
validatedObservable bug when the initial value is undefined

### ISSUE THREAD

**Issue by thj-dk** [Knockout-Contrib/Knockout-Validation#442]
When the initial value of the validatedObservable is undefined, an observable is created with the validated property set to true. This is a problem, because one would expect the validatedObservable to be enabled when setting a future object.

**Comment by mikocot** [comment]
I think the problem still persists if undefined is passed as the intial value . The code:

```javascript
ko.validatedObservable = function (initialValue, options) {
       if (!options && !kv.utils.isObject(initialValue)) {
		return ko.observable(initialValue).extend({ validatable: true });
	}
```

returns before it subscribed to the observable and therefore ko.validation.group is never called on the object, which finally causes the content is never being validated. On the other side... just pass anything (ex. true) in options and the issue is gone..

**Comment by crissdev** [comment]
@mikocot See the following tests for more clarification https://github.com/Knockout-Contrib/Knockout-Validation/blob/2.0.3/test/api-tests.js#L714-L744
There's no way to tell, if the method is called with undefined, if you want groupping or not. So the default behaviour is correct but a hint from the consumer of the API is required (eg. options = {}) in order to achieve the desired functionality.

**Comment by mikocot** [comment]
Thanks, the tests clearly show the expected usage, not that it looks good...

However, as I have noticed even passing an empty object doesnt solve the issue. The subscribe handler somehow updates the errors value to include direct properties, but at the same time the validatedObservables within it are not validated at all, until I reinitialize the validatedObservable, so basically:

```javascript
ko.validation.init{ ..., group{ deep: true, observable: true});

vm.entity = ko.validatedObservable();
...
vm.entity({ innerEntity : ko.validatedObservable( { /* some data */ }) }
//break innerEntity validation
vm.entity().innerEntity.isValid() // false
vm.entity.isValid() // true

vm.entity = ko.validatedObservable(vm.entity())
vm.entity.isValid() //false
```
