### ISSUE TITLE
Knockout-validation doesn't show error message with 'textInput' binding

### ISSUE THREAD

**Issue by ThakkarHitesh** [Knockout-Contrib/Knockout-Validation#451]
The textInput binding has been added in the latest version of knockout.js. However when using it with knockout-validation, the validation rules do apply but the validation message(s) is not displayed in UI when invalid. In fact the span with validationMessage class is missing completely in DOM for the element where textInput binding is used.

**Comment by naveen4854** [comment]
I can see this issue still happening

**Comment by fcogutierrez** [comment]
This link doesn't work https://github.com/Knockout-Contrib/Knockout-Validation/blob/master/Dist/knockout.validation.js#L962

Please, can you tell me how can I fix this issue? Thanks in advance.

**Comment by waynebloss** [comment]
I updated the link to point to the source code that existed at the time of my comment in October of 2014.

[Here is the new link to Line 962 of Dist/knockout.validation.js](https://github.com/Knockout-Contrib/Knockout-Validation/blob/309765748d362c17e554ed1e3dcee20ebfed3ca9/Dist/knockout.validation.js#L962) which shows you the section where you can add `kv.makeBindingHandlerValidatable("textInput");`.

However, this workaround only works for that version of the code. If you're using a newer version of Knockout, then I'm not sure what the problem is - I'm not using Knockout at this time.

**Comment by waynebloss** [comment]
It looks like the workaround was merged into Knockout by crissdev, which you can see in the 2 comments on October 31, 2014 and November 4, 2014.

The best thing to do in this case is to reproduce the problem using a tool like [jsfiddle.net](https://jsfiddle.net) and then post a link to your reproduction in a new issue for the current version of Knockout that you're using.
