### ISSUE TITLE
Knockout.Validation not showing error messages for property that is loaded after initial rendering

### ISSUE THREAD

**Issue by jgobl** [Knockout-Contrib/Knockout-Validation#556]
I have a Knockout.Validation scenario which I think would be fairly common but haven't found a solution from searching around the web and various answers on this site.

The property that I am validating does not get added to the knockout observable until after an ajax call. When validation gets triggered the validation fails and is an error in my validation group but the error message does not get shown on the page. I have made sure all the validation is hooked up by adding validation to a property that does exist when initial render happens and the message shows for that.

I know I could set a default for the property but I wouldn't expect you would have to do that. When i manually add the validation message with the validationMessage databind property it throws a js error because the property doesn't exist when knockout does its first pass through.....Uncaught TypeError: Unable to process binding "validationMessage: function (){return BlogPost().Title }" Message: Cannot read property 'extend' of undefined.

See this plunk for an example...http://plnkr.co/edit/OhUw8wP2uNypulbcOIbz?p=preview .

What am I missing here to get this working?

**Comment by crissdev** [comment]
:+1: for the detailed example. There are 2 problems preventing the example from working as expected. 
- The first one, `var validation = ko.validation.group(self, { deep: true });` you need `deep: true` in order to tell the Knockout-Validation to _walk_ inside `BlogPost` property.
- The second problem - currently not solved yet - see #398 and  http://stackoverflow.com/questions/29660281/knockout-validation-validation-not-binding-to-correct-instance-of-object - is somewhat tricky and requires more investigation. The current fix for this problem is to use the `with` binding: `<div class="form-group" data-bind="with: BlogPost()">`, and update the `value` binding to `value: $data.Title`.

One other thing, consider adding `observable: false` when you're creating the validation group ` var validation = ko.validation.group(self, { deep: true, observable: false });` if you intend to manually ask for errors.

Updated example: http://plnkr.co/edit/trpPpMcYdzKXgGXbyk9b?p=preview

**Comment by jgobl** [comment]
Thanks for the prompt response and solution to my problem. 

I had seen the deep:true setting and had been using it but must have taken it out at some stage when trying different variations to get it working. On your point about setting the validation group observable setting to false......based on the behaviour I was seeing I didnt think it was an observable by default. If I set the validation group up in the constructor function before the BlogPost property is filled then any errors are not subsequently added to the validation group property. See my amended example...http://plnkr.co/edit/65QljAuYNP9CqhCkQfrp. That is why i was doing the validation group stuff in the update function. Am I doing something wrong in the example or is that the expected behaviour of the validation group? If so then how would you usually suggest to best set up the validation in this scenario? 

Many thanks,

John

**Comment by crissdev** [comment]
Indeed the `observable` option of the group is `false` by default.

I noticed the example uses an earlier version of Knockout-Validation - `1.0.2`. I've updated the example to use the latest version in order to make your example working. The difference now is the line 26 `self.validation._updateState(this);` which tells the group to refresh its state. This method, although it's not recommended to be used directly in code, tells the group to traverse the validated object again. This method call is required if you don't ask for errors every time, like you did in your previous example.

If you can't update to `2.0.2` version - see Breaking Changes section in the [Release Notes](https://github.com/Knockout-Contrib/Knockout-Validation/releases/tag/2.0.0) then you can still use your first approach of asking for errors.

Updated example: http://plnkr.co/edit/uRJzKkt80DL3Lt8lgIwD?p=preview

---
I usually create some API to deal with validation - ie. apply rules or to keep the validation group consistent. Most of the times I have the view model's structure created upfront so I don't have such issues with validation.

Not the recommended I would say, but having the ViewModel cratead upfront and updating it with remote data (through repeated AJAX calls) will save you from such issues.
Ex:

```js
class BlogPost {
  constructor() {
    this.Title = ko.observable().extend({required: true})
  }
}

class MyComponent() {
  constructor() {
    this.blogPost = new BlogPost();
    this.validation = ko.validation.group(this, {deep: true});
  }

  init() {
    jQuery.ajax({ /* ajax options */ }).done((data) => {
     // Merge remote data with local data
     this.blogPost.Title(data.title);
     // Of course, if the list of properties is too long then you might consider
    // using ko.mapping plugin or create some helper method in your view model.
   });
  }
}
```

**Comment by jgobl** [comment]
Ok great....Many thanks for your suggestions and taking the time looking into this issue.

**Comment by maksimbykov** [comment]
I had same problem, nested observables with validation. So the one magic:
in `self.errors = ko.validation.group(self.submissionAnswers, { deep: true, live: true });`
pay attention on special additional param: object that contains field `live: true`
