### ISSUE TITLE
Does not require correctly with knockout-es5

### ISSUE THREAD

**Issue by grofit** [Knockout-Contrib/Knockout-Validation#602]
So when using knockout es5 you would do something like:

```
import * as ko from "knockout-es5"
// or 
var ko = require("knockout-es5");
````

and internally I think es5 wraps the knockout instance, however if I was to then do:

```
var ko = require("knockout-es5");
require("knockout-validation");
```

it does not extend the knockout instance returned from knockout es5, so validation never seems to be accessible via the knockout instance. If I were to do:

```
var ko = require("knockout");
require("knockout-validation");
```

It works fine and I can access `ko.validation`, I am not entirely sure how to fix it or best approach to get ko es5 working with validation so any advice would be great.

**Comment by crissdev** [comment]
@grofit `knockout-es5` should use `peerDependency` instead of `dependencies` in `package.json` - the same way `Knockout-Validation` does. One possible solution might be to shrinkwrap you dependencies but I'm not sure it works (I haven't tried it). Your best solution would be to fork that project and adjust it to your needs; then npm install from your fork.

See this example https://tonicdev.com/569fab1873c7940d00fa0d19/569fab1873c7940d00fa0d1a

**Comment by crissdev** [comment]
@grofit another example of using `peerDependencies` here https://github.com/crissdev/knockout.mapping/blob/master/package.json

**Comment by grofit** [comment]
ah ok so is this basically one of those issues where it is not sharing the same ko instance, so there are 2 active ones internally. Using peer dependencies will cause them both to resolve to the same one?

**Comment by crissdev** [comment]
Yes, that's correct.
https://nodejs.org/en/blog/npm/peer-dependencies/
