### ISSUE TITLE
Using observables with deep validation becomes incorrect when underlying collections change

### ISSUE THREAD

**Issue by tuscland** [Knockout-Contrib/Knockout-Validation#93]
At line 215, the comment says:
_`if using observables then traverse structure once and add observables`_

Validation becomes incorrect if the underlying collections changes (e.g. a new item is added to a validated view model collection) because the group has been built once for all.  There should be a way to manually rebuild the group, or there should be a fix so the group is rebuilt on child collection change.

**Comment by crissdev** [comment]
This issue has been resolved in 3dbd84d9d32d186b2a201c9017377309eb9fc13b but for `validatedObservable`. For the `group` method you may invoke the internal method `_updateState` but that API may change in the future.

In case someone else is getting here, I should point out that creating groups with `observable` option set, the previous created computed will still receive notifications, thus impacting performance.

The best and most correct approach would be to create the group with `observable: false` option.

I've updated the jsfiddle to work since it was unable to execute loaded script resources.
http://jsfiddle.net/db99yg73/
